shinesolutions/packer-aem

CHANGELOG.md
provisioners/puppet/modules/config/files/cloudwatch_writer.py

Added third Argument while loading Flusher module
Issue: https://github.com/shinesolutions/packer-aem/issues/58

Added third argument while loading Flusher module 

---

CHANGELOG.md
Makefile
provisioners/puppet/modules/config/data/RedHat/Amazon.yaml
provisioners/puppet/modules/config/data/RedHat/RedHat.yaml

Add Cloudwatch logs for content health check cron job

Add Cloudwatch logs for content health check cron job

---

CHANGELOG.md
provisioners/puppet/modules/config/data/RedHat/Amazon.yaml
provisioners/puppet/modules/config/data/RedHat/RedHat.yaml

* Add CloudWatch config for SSM commands offline-snapshot
* Add CloudWatch config for SSM commands offline-compaction-snapshot

Add new cloudwatch config

---

provisioners/bash/rhel7.sh

Nice and simple .. tested the link downloads the rpm.
Thank you Cliff

Fix issue with puppet repo changing path

---

templates/aws/author-publish-dispatcher.json
templates/aws/generic.json
templates/docker/generic.json

Sorry this is causing an error. I was meant to remove it when I removed the aem keystore inspec test

Remove invalid bash command

---

CHANGELOG.md
test/inspec/author-publish-dispatcher_spec.rb
test/inspec/author_spec.rb
test/inspec/publish_spec.rb

Extend component test to verify AEM Keystore contains the imported key #95

Extend component test to verify AEM Keystore contains the imported key

---

CHANGELOG.md
conf/ansible/inventory/group_vars/defaults.yaml
conf/puppet/hieradata/common.yaml
templates/ansible/hieradata.j2

- Update default Dispatcher download URL #103
- Update Apache Dispatcher Module version to 4.3.1

Update Dispatcher module

---

CHANGELOG.md
conf/ansible/inventory/group_vars/defaults.yaml
conf/puppet/hieradata/author-publish-dispatcher.yaml
conf/puppet/hieradata/common.yaml
docs/configuration.md
templates/ansible/hieradata.j2

* Hiera config paramter duplications
* Add paramter for defining aem healthcheck version

Removed hiera config paramter duplications

---

CHANGELOG.md
examples/aws/packer-instance-profile.yaml

S3 Bucket will be used to store artefacts
A bucket policy is included here to access the bucket artifacts and provided list bucket and get object access to the packer role

Changes to Packer Instance Profile cfn template to include s3 bucket creation

---

CHANGELOG.md
conf/ansible/inventory/group_vars/defaults.yaml

Refer https://helpx.adobe.com/experience-manager/dispatcher/release-notes.html
for the latest version

Upgrading dispatcher version to 4.3.2 (old version 4.3.1)

---

CHANGELOG.md
conf/puppet/hieradata/author-publish-dispatcher.yaml
conf/puppet/hieradata/common.yaml
templates/ansible/hieradata-author-publish-dispatcher.j2
templates/ansible/hieradata.j2

Changed hiera parameters for repository volume to data volume

Changed hiera parameters for repository volume to data volume

---

CHANGELOG.md
provisioners/puppet/modules/config/data/RedHat/Amazon.yaml
provisioners/puppet/modules/config/data/RedHat/RedHat.yaml

Add new AWS CloudWatch log resources [shinesolutions/aem-aws-stack-builder#298]

Add new AWS CloudWatch log resources

---

CHANGELOG.md
provisioners/puppet/modules/config/data/RedHat/Amazon-2.yaml
provisioners/puppet/modules/config/data/RedHat/Amazon.yaml
provisioners/puppet/modules/config/data/RedHat/CentOS-7.yaml
provisioners/puppet/modules/config/data/RedHat/CentOS.yaml
provisioners/puppet/modules/config/data/RedHat/RedHat.yaml

Removed bundler gem installation

Removed bundler gem installation

---

CHANGELOG.md
provisioners/puppet/modules/config/data/RedHat/RedHat.yaml

Add new `cloudwatch log to s3` cronjob logfile to Cloudwatch config

Add new `cloudwatch log to s3` cronjob logfile to Cloudwatch config

---

CHANGELOG.md
provisioners/bash/amazon-linux2.sh
provisioners/bash/centos7.sh
provisioners/bash/rhel7.sh

Add new RHEL7 repository to support the change of the RHEL7 repository 
names #182

Add new RHEL7 repository  #182

---

CHANGELOG.md
provisioners/puppet/modules/config/manifests/cloudwatch_metric_agent.pp

Customize AWS-Monitoring-tool
Add zip_url for AWS CloudWatch Monitoring tool

Fix cloud watch

---

CHANGELOG.md
conf/ansible/inventory/group_vars/defaults.yaml
conf/puppet/hieradata/author-publish-dispatcher.yaml
conf/puppet/hieradata/aws.yaml
conf/puppet/hieradata/common.yaml
conf/puppet/hieradata/docker.yaml
templates/ansible/hieradata-author-publish-dispatcher.j2
templates/ansible/hieradata.j2
templates/ansible/packer-vars.j2
templates/packer/aws/author-publish-dispatcher.json

Adding data_volume to Author-Dispatcher and Author-Publish

Shinesolutions/packer aem/30

---

CHANGELOG.md
provisioners/puppet/manifests/author-publish-dispatcher.pp
provisioners/puppet/manifests/author.pp
provisioners/puppet/manifests/dispatcher.pp
provisioners/puppet/manifests/java.pp
provisioners/puppet/manifests/publish.pp

Fixed dependency for stopping awslogs service #192

Fixed dependency for stopping awslogs service #192

---

CHANGELOG.md
provisioners/puppet/manifests/dispatcher.pp

Added Dispatchers data volume to metric agent

Update Metric agent with Dispatchers data volume 

---

CHANGELOG.md
conf/ansible/inventory/group_vars/defaults.yaml
docs/configuration.md
provisioners/ansible/library/packer_template.py
provisioners/ansible/playbooks/set-config.yaml
templates/ansible/packer-vars.j2
templates/packer/aws/author-publish-dispatcher.json
templates/packer/aws/generic.json

Add EBS Volume encryption support
- Add feature to enable EBS Volume encryption when Baking #198
- Add feature to define CMK for enabling EBS Volume encryption #198

Add EBS Volume encryption support

---

CHANGELOG.md
provisioners/bash/amazon-linux2.sh
provisioners/bash/centos7.sh
provisioners/bash/rhel7.sh

Lockdown puppet-agent version to 5.5.20 [#218]

Lockdown puppet-agent version to 5.5.20 [#218]

---

CHANGELOG.md
templates/cloudformation/aws-resources.yaml

- Add support to retrieve SSL Certificate from IAM
- Add support to retrieve SSL Certificate from IAM to support 4096-bit 
RSA keys or EC keys

Add support to retrieve SSL Certificate from IAM

---

test/inspec/author-publish-dispatcher_spec.rb
test/inspec/dispatcher_spec.rb

Update Dispatcher Component InSpec test

Update Dispatcher Component InSpec test

---

CHANGELOG.md
Puppetfile
conf/ansible/inventory/group_vars/defaults.yaml
conf/packer/vars/components/author-publish-dispatcher.json
conf/packer/vars/components/author.json
conf/packer/vars/components/base.json
conf/packer/vars/components/dispatcher.json
conf/packer/vars/components/java.json
conf/packer/vars/components/publish.json
docs/configuration.md
provisioners/puppet/manifests/author-publish-dispatcher.pp
provisioners/puppet/manifests/author.pp
provisioners/puppet/manifests/dispatcher.pp
provisioners/puppet/manifests/java.pp
provisioners/puppet/manifests/publish.pp
provisioners/puppet/modules/config/files/nvme/ebsnvme-id.py
provisioners/puppet/modules/config/files/nvme/ec2nvme-nsid.sh
provisioners/puppet/modules/config/files/nvme/udev.rules
provisioners/puppet/modules/config/manifests/init.pp
templates/ansible/packer-vars.j2
test/inspec/author-publish-dispatcher_spec.rb
test/inspec/dispatcher_spec.rb

- Add support for NVME Devices [#207]
- Add new configuration parameter to configure EC2 instance type for AMI 
creation [#207]
- Changed default EC2 instance type for AMI creation to `m5.2xlarge`

Add support for NVME Devices

---

CHANGELOG.md
provisioners/puppet/modules/config/data/RedHat/Amazon-2.yaml
provisioners/puppet/modules/config/data/RedHat/Amazon.yaml
provisioners/puppet/modules/config/data/RedHat/CentOS-7.yaml
provisioners/puppet/modules/config/data/RedHat/CentOS.yaml
provisioners/puppet/modules/config/data/RedHat/RedHat.yaml

Lockdown Inspec dependency `parallel` version `1.19.2` [#231]

Lockdown Inspec dependency `parallel` version `1.19.2` [#231]

---

CHANGELOG.md
provisioners/puppet/modules/config/data/RedHat/Amazon-2.yaml
provisioners/puppet/modules/config/data/RedHat/Amazon.yaml
provisioners/puppet/modules/config/data/RedHat/CentOS-7.yaml
provisioners/puppet/modules/config/data/RedHat/CentOS.yaml
provisioners/puppet/modules/config/data/RedHat/RedHat.yaml

Upgrade `ruby_aem` to 3.10.1

---

CHANGELOG.md
provisioners/bash/rhel7.sh

Function added to check puppet version, and skip installing it if it is already installed.

Added condition to install puppet if it is not already installed in the base AMI #245

---

CHANGELOG.md
conf/ansible/inventory/group_vars/defaults.yaml
docs/configuration.md
templates/ansible/hieradata.j2

- Add new configuration parameter `library.aem_healthcheck_source` to define the source of the AEM Content Healthcheck

Add new configuration parameter `library.aem_healthcheck_source`

---

CHANGELOG.md
provisioners/puppet/modules/config/manifests/base.pp

- Disabled installation of collectd-python for Amazon Linux 2 #268
- Fixed AMI Baking for Amazon Linux 2 #268

Fixed AMI Baking for Amazon Linux 2 #268

---

CHANGELOG.md
Puppetfile

- Upgrade puppet-aem-curator to 3.28.2

Upgrade puppet-aem-curator to 3.28.2
